import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./schema"; // generated by openapi-typescript

const ABANTU_API_URL = "http://192.168.0.237:3000";

const fetchClient = createFetchClient<paths>({
  baseUrl: ABANTU_API_URL,
});

export const api = createClient(fetchClient);

