/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/vocab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** get all the vocab n shit */
        get: {
            parameters: {
                query?: {
                    type?: string | null;
                    search?: string | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            xhosa: string;
                            english: string;
                            illustration?: string | null;
                            nounClass?: string | null;
                            type: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** insert all the vocab lol */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        xhosa: string;
                        english: string;
                        illustration?: string | null;
                        nounClass?: string | null;
                        type: string;
                    }[];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            xhosa: string;
                            english: string;
                            illustration?: string | null;
                            nounClass?: string | null;
                            type: string;
                        }[];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vocab/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a single vocab record by id. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            xhosa: string;
                            english: string;
                            illustration?: string | null;
                            nounClass?: string | null;
                            type: string;
                        };
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Update a given vocab by id */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        xhosa?: string | null;
                        english?: string | null;
                        illustration?: string | null;
                        nounClass?: string | null;
                        type?: string | null;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            xhosa: string;
                            english: string;
                            illustration?: string | null;
                            nounClass?: string | null;
                            type: string;
                        }[];
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        /** Delete a vocab by id */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all courses */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            name: string;
                            language: string;
                            /** @enum {unknown} */
                            status: [
                                "in-progress",
                                "review",
                                "published"
                            ];
                            creator?: {
                                id: number;
                                email: string;
                                firstname: string;
                                lastname: string;
                                emailVerified?: boolean;
                                onboarded: boolean;
                                mobile: string;
                                profileImage?: string;
                            } | null;
                            units: {
                                id: number;
                                name: string;
                                description: string;
                                level: number;
                                creatorId?: number;
                            }[];
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Create a new course */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        language: string;
                        units: {
                            name: string;
                            description: string;
                            level: number;
                        }[];
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            name: string;
                            language: string;
                            /** @enum {unknown} */
                            status: [
                                "in-progress",
                                "review",
                                "published"
                            ];
                            creator?: {
                                id: number;
                                email: string;
                                firstname: string;
                                lastname: string;
                                emailVerified?: boolean;
                                onboarded: boolean;
                                mobile: string;
                                profileImage?: string;
                            } | null;
                            units: {
                                id: number;
                                name: string;
                                description: string;
                                level: number;
                                creatorId?: number;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific course with all units by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            name: string;
                            language: string;
                            /** @enum {unknown} */
                            status: [
                                "in-progress",
                                "review",
                                "published"
                            ];
                            creator?: {
                                id: number;
                                email: string;
                                firstname: string;
                                lastname: string;
                                emailVerified?: boolean;
                                onboarded: boolean;
                                mobile: string;
                                profileImage?: string;
                            } | null;
                            units: {
                                id: number;
                                name: string;
                                description: string;
                                level: number;
                                creatorId?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Update course details for the given course by id */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string | null;
                        language?: string | null;
                        status?: [
                            "in-progress",
                            "review",
                            "published"
                        ] | null;
                        creatorId?: number | null;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            name: string;
                            language: string;
                            /** @enum {unknown} */
                            status: [
                                "in-progress",
                                "review",
                                "published"
                            ];
                            creator?: {
                                id: number;
                                email: string;
                                firstname: string;
                                lastname: string;
                                emailVerified?: boolean;
                                onboarded: boolean;
                                mobile: string;
                                profileImage?: string;
                            } | null;
                            units: {
                                id: number;
                                name: string;
                                description: string;
                                level: number;
                                creatorId?: number;
                            }[];
                        };
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        /** Delete the course and all associated units with the given course id */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{id}/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** get all units with the given course id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            name: string;
                            description: string;
                            level: number;
                            creatorId?: number;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Create new empty units */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        description: string;
                        level: number;
                    }[];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            name: string;
                            description: string;
                            level: number;
                            creatorId?: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/units/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** get a unit by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            name: string;
                            description: string;
                            level: number;
                            creatorId?: number;
                        };
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            data: {
                                message: string;
                            };
                        };
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** Update a unit with a given id */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        id?: number;
                        name?: string;
                        description?: string;
                        level?: number;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            name: string;
                            description: string;
                            level: number;
                            creatorId?: number;
                        };
                    };
                };
            };
        };
        /** delete new empty units */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            data: {
                                message: string;
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/units/{id}/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all exercises for a unit with given id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            unitId?: number;
                            /** @enum {unknown} */
                            questionType?: [
                                "translation",
                                "multiple-choice"
                            ];
                            question: string;
                            options: string[];
                            answers: (string[] | string)[];
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Add exercises to a unit with given id */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {unknown} */
                        questionType?: [
                            "translation",
                            "multiple-choice"
                        ];
                        question: string;
                        options: string[];
                        answers?: (string[] | string)[] | null;
                    }[];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an exercises by a given id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            unitId?: number;
                            /** @enum {unknown} */
                            questionType?: [
                                "translation",
                                "multiple-choice"
                            ];
                            question: string;
                            options: string[];
                            answers: (string[] | string)[];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Update an exercises by a given id */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        unitId?: number | null;
                        questionType?: [
                            "translation",
                            "multiple-choice"
                        ] | null;
                        question?: string | null;
                        options?: string[] | null;
                        answers?: (string[] | string)[] | null;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            unitId?: number;
                            /** @enum {unknown} */
                            questionType?: [
                                "translation",
                                "multiple-choice"
                            ];
                            question: string;
                            options: string[];
                            answers: (string[] | string)[];
                        };
                    };
                };
            };
        };
        /** Delete an exercise by a given id */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
